name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'type:new'
  - title: '🐞 Tests Fixes'
    labels:
      - 'type:fix'
  - title: '🔬 Other'
    labels:
      - 'type:other'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES

  ## 👀 Links

  [Commits since $PREVIOUS_TAG](https://github.com/qagid/github-actions/compare/$PREVIOUS_TAG...master)
